[versions]
agp = "8.13.1"
kotlin = "2.2.10"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"

#Decompose
decomposeVer = "3.4.0"
serializationJson = "1.9.0"
extensionsVer = "2.5.0"

#Room
roomVer = "2.8.3"

#Hilt
hiltVer = "2.57.1"

#Coroutines
corVer = "1.3.9"

#Plugins
serializationPlugin = "2.2.21"
kspVer = "2.2.10-2.0.2"

appcompat = "1.6.1"
material = "1.10.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

#Decompose
decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decomposeVer" }
decompose-extensions = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decomposeVer" }
decompose-extensions-jetpack = { group = "com.arkivanov.decompose", name = "extensions-compose-jetpack", version.ref = "decomposeVer" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }

#Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVer" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVer" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVer" }

#Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVer" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hiltVer" }

#Coroutines
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "corVer" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "corVer" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

#Add Plugins
serialization-plugin = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serializationPlugin" }
ksp-plugin = { id = "com.google.devtools.ksp", version.ref = "kspVer" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltVer" }
android-library = { id = "com.android.library", version.ref = "agp" }